#!/bin/sh
rails librarian -m http://github.com/snusnu/rails-templates/raw/master/dm_rails_master.rb
cd librarian
rails generate scaffold Asset name:string
sed s/dm_rails3_app/db\/librarian/g database.yml > database.yaml
rake db:create
rake db:autoupgrade
