defaults: &defaults
  adapter: sqlite3

development:
  database: db/librarian_development.db
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgresql
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/librarian_test.db
  <<: *defaults
production:
  database: db/librarian_production.db
  <<: *defaults
